route:
  receiver: telegram
  group_by: ['alertname']
  group_wait: 10s

templates:
  - /app/templates/*.tmpl

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: $TELEGRAM_BOT_TOKEN
        chat_id: $TELEGRAM_CHAT_ID
        send_resolved: false
        message: '{{ template "telegram.message" . }}'
