global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 1m
  body_size_limit: 15MB

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: docker
    static_configs:
      - targets:
        - cadvisor:8080
        - host.docker.internal:9323

  - job_name: smartctl
    static_configs:
      - targets: ['smartctl-exporter:9633']
